### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Mizuki-hhh** [Mizuki-hhh/protospace-33010#1]
# URL
https://protospace-33010.herokuapp.com/

**Comment by Nishi0418** [comment]
Mizuki-hhhさん
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・proto編集ページにて
- 入力箇所を空欄にして保存を押した後、再度全ての入力箇所を入力し保存をすると以下のエラーが表示されます。
<img width="1440" alt="スクリーンショット 2020-12-16 19 04 16" src="https://user-images.githubusercontent.com/51874745/102334218-c45bd700-3fd1-11eb-9b2e-9c0eae6b705d.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Mizuki-hhh** [comment]
ご確認ありがとうございます！！

proto編集ページにて
入力箇所を空欄にして保存を押した後、再度入力した際のエラーを修正いたしました。
インスタンス変数になっていなかったことが原因と考えられます。

お手数ですが、もう一度ご確認のほど、
よろしくお願い申し上げます。

**Comment by Nishi0418** [comment]
Mizuki-hhhさん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
